source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!

target 'jjollaejjollae' do
  pod 'SwiftLint'
  pod 'Kingfisher', '~> 6.0'
  pod 'Moya', '~> 14.0'
  pod 'XLPagerTabStrip', '~> 9.0'
  pod 'FSCalendar'
  pod 'NMapsMap'

end
