source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
end

target 'jjollaejjollae' do
  pod 'SwiftLint'
  pod 'Kingfisher', '~> 6.0'
  pod 'Moya', '~> 14.0'
  pod 'FSCalendar'
  pod 'NMapsMap'
  pod 'naveridlogin-sdk-ios'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'KakaoSDKTalk'
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'
  pod 'Gifu'
  pod 'Toast-Swift', '~> 5.0.1'


  pod 'SwiftyJSON', '~> 4.0'

end
